In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [3]:
order=pd.read_csv('/Users/rickie/Desktop/czbank_test/olist_orders_dataset.csv')
cust=pd.read_csv('/Users/rickie/Desktop/czbank_test/olist_customers_dataset.csv')
prd=pd.read_csv('/Users/rickie/Desktop/czbank_test/olist_order_items_dataset.csv')

prd

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40
10,00061f2a7bc09da83e415a52dc8a4af1,1,d63c1011f49d98b976c352955b1c4bea,cc419e0650a3c5ba77189a1882b7556a,2018-03-29 22:28:09,59.99,8.88
11,00063b381e2406b52ad429470734ebd5,1,f177554ea93259a5b282f24e33f65ab6,8602a61d680a10a82cceeeda0d99ea3d,2018-07-31 17:30:39,45.00,12.98
12,0006ec9db01a64e59a68b2c340bf65a7,1,99a4788cb24856965c36a24e339b6058,4a3ca9315b744ce9f8e9374361493884,2018-07-26 17:24:20,74.00,23.32
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
15,0009792311464db532ff765bf7b182ae,1,8cab8abac59158715e0d70a36c807415,530ec6109d11eaaf87999465c6afee01,2018-08-17 12:15:10,99.90,27.65
16,0009c9a17f916a706d71784483a5d643,1,3f27ac8e699df3d300ec4a5d8c5cf0b2,fcb5ace8bcc92f75707dc0f01a27d269,2018-05-02 09:31:53,639.00,11.34
17,000aed2e25dbad2f9ddb70584c5a2ded,1,4fa33915031a8cde03dd0d3e8fb27f01,fe2032dab1a61af8794248c8196565c9,2018-05-16 20:57:03,144.00,8.77
18,000c3e6612759851cc3cbb4b83257986,1,b50c950aba0dcead2c48032a690ce817,218d46b86c1881d022bce9c68a7d4b15,2017-08-21 03:33:13,99.00,13.71
19,000e562887b1f2006d75e0be9558292e,1,5ed9eaf534f6936b51d0b6c5e4d5c2e9,8cbac7e12637ed9cffa18c7875207478,2018-02-28 12:08:37,25.00,16.11
20,000e63d38ae8c00bbcb5a30573b99628,1,553e0e7590d3116a072507a3635d2877,1c129092bf23f28a5930387c980c0dfc,2018-03-29 20:07:49,47.90,8.88
21,000e906b789b55f64edcb1f84030f90d,1,57d79905de06d8897872c551bfd09358,ea8482cd71df3c1969d7b9473ff13abc,2017-11-27 19:09:02,21.99,11.85
22,000f25f4d72195062c040b12dce9a18a,1,1c05e0964302b6cf68ca0d15f326c6ba,7c67e1448b00f6e969d365cea6b010ab,2018-03-21 11:10:11,119.99,44.40
23,001021efaa8636c29475e7734483457d,1,5d7c23067ed3fc8c6e699b9373d5890b,6560211a19b47992c3666cc44a7e94c0,2018-03-05 09:35:41,49.00,15.10
24,0010b2e5201cc5f1ae7e9c6cc8f5bd00,1,5a419dbf24a8c9718fe522b81c69f61a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-09-15 18:04:37,48.90,16.60
25,00119ff934e539cf26f92b9ef0cdfed8,1,21b1c2f67a9aafb5af0eb06c13b9dbda,c864036feaab8c1659f65ea4faebe1da,2017-08-11 00:35:12,219.90,16.98
26,0011d82c4b53e22e84023405fb467e57,1,c389f712c4b4510bc997cee93e8b1a28,bfd27a966d91cfaafdb25d076585f0da,2018-01-29 21:51:25,289.00,26.33
27,00125cb692d04887809806618a2a145f,1,1c0c0093a48f13ba70d0c6b0a9157cb7,41b39e28db005d9731d9d485a83b4c38,2017-03-29 13:05:42,109.90,25.51
28,00130c0eee84a3d909e75bc08c5c3ca1,1,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-06-14 05:16:24,27.90,7.94
29,0013503b13da1eac686219390b7d641b,1,38afdf723b95d455b418a0f57d623c6b,1554a68530182680ad5c8b042c3ab563,2017-12-13 03:16:36,119.90,17.32
...,...,...,...,...,...,...,...
112620,ffeeb911d070bea3dd20bd5fd01da5e8,1,a5341e3f8155dbb3e62323d3ea289729,ff063b022a9a0aab91bad2c9088760b7,2017-10-13 19:25:54,79.50,16.19
112621,ffef98cd5ecdc992fefbd967549520dd,1,11fd9d7ba552e1d28872e008acf1e050,cb8bcce248bb1fb274ba762d8b971456,2017-07-06 03:15:21,139.90,13.11
112622,ffef9e1de5dd07b397b373f9bb72cccf,1,30ac6df06dc59ad72cf2f158fc2d904c,0dd184061fb0eaa7ca37932c68ab91c5,2018-01-17 10:14:27,94.00,21.50
112623,ffefb169ddf34cecc0622a6d3cc387f8,1,601a360bd2a916ecef0e88de72a6531a,7a67c85e85bb2ce8582c35f2203ad736,2017-07-06 19:35:09,129.99,12.11
112624,fff0db5573c78c1cb5a2b68a2bbd8d4a,1,681953ccd5c33207d75571a4bfbe127d,777a0c55737f34ffeb78010f7542ab41,2018-07-03 09:31:23,69.95,7.75
112625,fff1e3e76b816bfe8ef16678cc53c643,1,2e910736c31392d46841f315e9511405,7a67c85e85bb2ce8582c35f2203ad736,2018-03-05 09:08:53,65.99,20.86
112626,fff2cdc825f9fc0ba3c04227cfa02303,1,044f05bc9de36e8a693a83e4bc79dd0d,ea8482cd71df3c1969d7b9473ff13abc,2018-02-08 02:52:42,24.99,25.63
112627,fff2e9e3aa8644e19710216b4ef53ab2,1,7340a3839a1de1e99d149b8cf052a2ec,4a3ca9315b744ce9f8e9374361493884,2017-06-01 02:42:42,69.90,16.25
112628,fff3983dfa3c5a0d752d8d17baa406a0,1,092be1e8336fc404c57bd5970d056886,cbd996ad3c1b7dc71fd0e5f5df9087e2,2018-07-16 22:05:13,66.39,14.05
112629,fff60e5408a9dd1e92ee30023052af30,1,1a405418406359cc2b8815f93bf359c2,4d6d651bd7684af3fffabd5f08d12e5a,2018-02-05 10:55:55,129.90,18.80
112630,fff6889749958e42b47a7977a4cf0ea0,1,75f6a4f019ec1322758d53b2fee2cc12,058cb5aeb36d7c0fcae20fc85d5e0a59,2017-10-01 22:56:15,92.00,31.60
112631,fff6b8ca971f8e3ec822e99d0f2d3d21,1,9afaad66aca8b0c79e4f084a89c9c92b,42bde9fef835393bb8a8849cb6b7f245,2017-09-21 12:04:29,199.00,16.83
112632,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.00,20.91
112633,fff8286f77788ab8b55b2e5747fa7dd8,1,a2da86fa759178e9e58e54aa1a144e59,ea8482cd71df3c1969d7b9473ff13abc,2018-07-05 22:31:13,24.99,15.28
112634,fff8287bbae429a99bb7e8c21d151c41,1,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112636,fff90cdcb3b2e6cfb397d05d562fd3fe,1,764292b2b0f73f77a0272be03fdd45f3,bd23da7354813347129d751591d1a6e2,2017-11-30 10:11:28,89.90,11.83
112637,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.90,44.02
112638,fffb0b1a50e65c449020434fa835e078,1,e7be84ea9462aac5e2b0b08eb35ba7f1,36a968b544695394e4e9d7572688598f,2017-04-28 16:45:12,4.90,10.96
112639,fffb2ef8874127f75b52b643880fd7e0,1,ebceb9726cf5c6187b48e17fe58747b0,609e1a9a6c2539919b8205cf7c4e6ff0,2018-04-09 05:08:33,17.90,22.06
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [4]:
data=pd.merge(order,cust,on='customer_id')
data=pd.merge(data,prd,on='order_id')
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [5]:
data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110180 entries, 0 to 112649
Data columns (total 18 columns):
order_id                         110180 non-null object
customer_id                      110180 non-null object
order_status                     110180 non-null object
order_purchase_timestamp         110180 non-null object
order_approved_at                110180 non-null object
order_delivered_carrier_date     110180 non-null object
order_delivered_customer_date    110180 non-null object
order_estimated_delivery_date    110180 non-null object
customer_unique_id               110180 non-null object
customer_zip_code_prefix         110180 non-null int64
customer_city                    110180 non-null object
customer_state                   110180 non-null object
order_item_id                    110180 non-null int64
product_id                       110180 non-null object
seller_id                        110180 non-null object
shipping_limit_date              110180 non-null object
price                            110180 non-null float64
freight_value                    110180 non-null float64
dtypes: float64(2), int64(2), object(14)
memory usage: 16.0+ MB

In [6]:
price_m=data['price'].mean()
data.customer_city.value_counts()

sao paulo                    17400
rio de janeiro                7593
belo horizonte                3087
brasilia                      2341
curitiba                      1727
campinas                      1626
porto alegre                  1572
salvador                      1358
guarulhos                     1293
sao bernardo do campo         1041
niteroi                        958
santo andre                    873
osasco                         831
santos                         813
goiania                        784
sao jose dos campos            758
fortaleza                      694
sorocaba                       688
recife                         656
florianopolis                  650
jundiai                        642
ribeirao preto                 571
nova iguacu                    487
belem                          477
contagem                       477
juiz de fora                   470
barueri                        469
mogi das cruzes                435
sao goncalo                    421
vitoria                        420
                             ...
heliopolis                       1
ceilandia                        1
presidente lucena                1
aragoiania                       1
alvorada do gurgueia             1
lagoa da canoa                   1
pacotuba                         1
sao joaquim do monte             1
sobralia                         1
paulistania                      1
monte alegre de sergipe          1
capivari do sul                  1
dom joaquim                      1
herveiras                        1
frei rogerio                     1
varzea do poco                   1
presidente nereu                 1
sao sebastiao da amoreira        1
jose da penha                    1
brasilandia                      1
ilicinea                         1
parnarama                        1
minas do leao                    1
aracatu                          1
sao mateus de minas              1
iomere                           1
goncalves dias                   1
pancas                           1
jerico                           1
lagoa dos tres cantos            1
Name: customer_city, Length: 4085, dtype: int64

In [7]:
data.groupby('customer_id').price.mean().reset_index().price

0          89.800000
1          54.900000
2         179.990000
3         149.900000
4          93.000000
5          59.990000
6          34.300000
7         120.900000
8          69.990000
9        1107.000000
10        134.900000
11         47.990000
12         49.900000
13         89.900000
14        159.900000
15         15.000000
16         89.900000
17        122.900000
18         53.990000
19         29.990000
20         29.900000
21         83.990000
22         49.970000
23         49.900000
24         29.900000
25        349.900000
26        149.900000
27         79.900000
28         18.820000
29        199.900000
            ...
96431      46.330000
96432      59.900000
96433      48.990000
96434      64.900000
96435     144.410000
96436      15.900000
96437      13.900000
96438      92.900000
96439      49.990000
96440     199.000000
96441       9.900000
96442      69.000000
96443      48.900000
96444      75.000000
96445      13.650000
96446     144.000000
96447      14.900000
96448      39.990000
96449      59.900000
96450     152.990000
96451      30.000000
96452      79.000000
96453      66.296667
96454      35.000000
96455      45.900000
96456      78.000000
96457      54.900000
96458      47.900000
96459     199.900000
96460      10.900000
Name: price, Length: 96461, dtype: float64

In [8]:
def if_high(x):
    if x>=price_m:
        return 'high'
    else:
        return 'average'
data['type']=data.groupby('customer_id').price.mean().reset_index().price.apply(if_high)

In [33]:

cnt=data.pivot_table('order_id',columns='type',index=['customer_state'],aggfunc='count')
cnt['total']=cnt['high']+cnt['average']
cnt['high_pct']=cnt['high']/cnt['total']

# cnt['high_pct'] = cnt['high_pct'].apply(lambda x: format(x, '.2%')) 
cnt
cnt['total_pct']=cnt['high'].sum()/cnt['total'].sum()
cnt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, AC to TO
Data columns (total 5 columns):
average      27 non-null int64
high         27 non-null int64
total        27 non-null int64
high_pct     27 non-null float64
total_pct    27 non-null float64
dtypes: float64(2), int64(3)
memory usage: 1.3+ KB

In [40]:
cnt['tgi']=cnt['high_pct']/cnt['total_pct']*100
tgi=cnt[cnt['total']>cnt['total'].median()]
tgi.sort_values(by='tgi',ascending=False)

type            average   high  total  high_pct  total_pct         tgi
customer_state
BA                 2160   1004   3164  0.317320   0.307859  103.073215
MG                 7483   3452  10935  0.315684   0.307859  102.541717
CE                  859    385   1244  0.309486   0.307859  100.528438
PR                 3342   1496   4838  0.309219   0.307859  100.441760
SP                27501  12239  39740  0.307977   0.307859  100.038382
RS                 3637   1618   5255  0.307897   0.307859  100.012523
RJ                 8430   3731  12161  0.306800   0.307859   99.656251
DF                 1402    609   2011  0.302834   0.307859   98.367992
SC                 2457   1065   3522  0.302385   0.307859   98.222016
ES                 1337    578   1915  0.301828   0.307859   98.040981
PA                  649    275    924  0.297619   0.307859   96.673915
GO                 1371    572   1943  0.294390   0.307859   95.625081
PE                 1057    439   1496  0.293449   0.307859   95.319447